package com.xialinrui.imperial.court.mapper;

import com.xialinrui.imperial.court.entity.Memorials;
import com.xialinrui.imperial.court.entity.MemorialsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MemorialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 14 14:20:53 CST 2022
     */
    int countByExample(MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 14 14:20:53 CST 2022
     */
    int deleteByExample(MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 14 14:20:53 CST 2022
     */
    int deleteByPrimaryKey(Integer memorialsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 14 14:20:53 CST 2022
     */
    int insert(Memorials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 14 14:20:53 CST 2022
     */
    int insertSelective(Memorials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 14 14:20:53 CST 2022
     */
    List<Memorials> selectByExample(MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 14 14:20:53 CST 2022
     */
    Memorials selectByPrimaryKey(Integer memorialsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 14 14:20:53 CST 2022
     */
    int updateByExampleSelective(@Param("record") Memorials record, @Param("example") MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 14 14:20:53 CST 2022
     */
    int updateByExample(@Param("record") Memorials record, @Param("example") MemorialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 14 14:20:53 CST 2022
     */
    int updateByPrimaryKeySelective(Memorials record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_memorials
     *
     * @mbggenerated Sun Aug 14 14:20:53 CST 2022
     */
    int updateByPrimaryKey(Memorials record);

    List<Memorials> selectAllMemorialsDigest();

    Memorials selectMemorialsById(@Param("memorials_id") String memorialsId);

    void updateMemorialsStatusToRead(@Param("memorials_id") String memorialsId);

    void updateMemorialsFeedback(@Param("memorials_id") String memorialsId, @Param("feedback_content") String feedbackContent);

}